feed/urls.py
from django.urls import path 

from . import views 

app_name = "feed"

urlpatterns = [
    path("", views.HomePage.as_view(), name="index")
]

myblog/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path
from django.conf.urls import include

from writeups import urls as writeups_urls 
from feed import urls as feed_urls 


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(writeups_urls, namespace='writeups')),
    path('', include(feed_urls, namespace='feed')),
    path("", include("allauth.urls")),
] 

if settings.DEBUG: 
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

writeups/urls.py
from django.urls import path
from .views import HomePageView, PostDetailView, AddPostView

app_name = 'writeups'

urlpatterns = [
    path('', HomePageView.as_view(), name='index'),
    path('details/<int:pk>', PostDetailView.as_view(), name='detail'),
    path('post/', AddPostView.as_view(), name='post' ),   
]

feed/models.py
from django.db import models

class Post(models.Model):
    text = models.CharField(max_length=240)
    date = models.DateTimeField(auto_now=True)

    def __str__(self) :
        return self.text[0:100]

writeups/models.py
from django.db import models
from sorl.thumbnail import ImageField

class Post(models.Model):
    text = models.CharField(max_length=140, blank=False, null=False)
    image = ImageField()

    def __str__(self):
        return self.text  

writeups/forms.py
from django import forms 
 
class PostForm(forms.Form):
    text = forms.CharField()
    image = forms.FileField()

feed/views.py
from django.views.generic import ListView

from .models import Post


class HomePage(ListView):
    http_method_names = ["get"]
    template_name = "homepage.html"
    model = Post
    context_object_name = "posts"
    queryset = Post.objects.all().order_by('-id')[0:30]

writeups/views.py
from typing import Any
#  ccbv.co.uk
from django.contrib import messages
from django.views.generic import TemplateView, DetailView, FormView

from .forms import PostForm
from .models import Post

class HomePageView(TemplateView):
    template_name = "home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['posts'] = Post.objects.all().order_by('-id')
        return context
    
class PostDetailView(DetailView):
    template_name = "detail.html"
    model = Post


class AddPostView(FormView):
    template_name = "new_post.html"
    form_class = PostForm
    success_url = "/"

    def dispatch(self, request, *args, **kwargs):
        self.request = request
        return super().dispatch(request, *args, **kwargs)
        
    def form_valid(self, form):
        new_object = Post.objects.create(
            text=form.cleaned_data['text'],
            image=form.cleaned_data['image']
        )
        messages.add_message(self.request, messages.SUCCESS, 'Your post was successful')
        return super().form_valid(form)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Default Title{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" />
</head>
<body>

    <!-- component -->

    /* Estilos para el señalador de posición (border-left) */
    .sidebar li:hover a::before {
      content: "";
      position: absolute;
      top: 0;
      left: 0;
      height: 100%;
      width: 4px;
      background: linear-gradient(to bottom, #00FFFF, #008080); /* Gradiente cyan */
    }

    /* Estilos para cambiar el color del ícono y el texto a blanco al pasar el cursor */
    .sidebar li:hover a i,
    .sidebar li:hover a span {
      color: white;
    }


  <!-- Sidebar -->
  <div class="fixed flex flex-col top-14 left-0 w-14 hover:w-64 md:w-64 bg-white h-full text-gray-600 transition-all duration-300 border-none z-10 sidebar">
    <div class="overflow-y-auto overflow-x-hidden flex flex-col justify-between flex-grow">
      <ul class="flex flex-col py-4 space-y-1">
        <li>
          <a href="#" class="relative flex flex-row items-center h-11 focus:outline-none hover:bg-cyan-500 text-gray-600 hover:text-gray-800 border-l-4 border-transparent">
            <!-- Icono Home de Font Awesome -->
            <span class="inline-flex justify-center items-center ml-4">
              <i class="fas fa-home"></i>
            </span>
            <span class="ml-2 text-sm tracking-wide truncate">Home</span>
          </a>
        </li>
        <li>
          <a href="#" class="relative flex flex-row items-center h-11 focus:outline-none hover:bg-cyan-500 text-gray-600 hover:text-gray-800 border-l-4 border-transparent">
            <!-- Icono Check Circle de Font Awesome -->
            <span class="inline-flex justify-center items-center ml-4">
              <i class="fas fa-check-circle"></i>
            </span>
            <span class="ml-2 text-sm tracking-wide truncate">Authors</span>
          </a>
        </li>
        <li>
          <a href="#" class="relative flex flex-row items-center h-11 focus:outline-none hover:bg-cyan-500 text-gray-600 hover:text-gray-800 border-l-4 border-transparent">
            <!-- Icono Users de Font Awesome -->
            <span class="inline-flex justify-center items-center ml-4">
              <i class="fas fa-users"></i>
            </span>
            <span class="ml-2 text-sm tracking-wide truncate">Articles</span>
          </a>
        </li>
        <li>
          <a href="#" class="relative flex flex-row items-center h-11 focus:outline-none hover:bg-cyan-500 text-gray-600 hover:text-gray-800 border-l-4 border-transparent">
            <!-- Icono Store de Font Awesome -->
            <span class="inline-flex justify-center items-center ml-4">
              <i class="fas fa-store"></i>
            </span>
            <span class="ml-2 text-sm tracking-wide truncate">Sign Up</span>
          </a>
        </li>
        <li>
          <a href="#" class="relative flex flex-row items-center h-11 focus:outline-none hover:bg-cyan-500 text-gray-600 hover:text-gray-800 border-l-4 border-transparent">
            <!-- Icono Sign Out de Font Awesome -->
            <span class="inline-flex justify-center items-center ml-4">
              <i class="fas fa-sign-out-alt"></i>
            </span>
            <span class="ml-2 text-sm tracking-wide truncate">Cerrar Sesión</span>
          </a>
        </li>
      </ul>
    </div>
  </div>
  <!-- ./Sidebar -->

    {% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
{% include "includes/navbar.html" %}


    <div class="container">
    {% block body %}{% endblock %}
</div>
</body>
</html>

templates/detail.html
{% extends "base.html" %}

{% block title%}{{ object.text }}{% endblock %}

{% block body %}
    <!-- <a href="{% url 'writeups:index' %}">&larr; Go back</a> -->
    <div class="row">
        <!-- <div class="col-sm-20 offset-sm-1">  -->
            {{ object.text }}
            <img src="{{ object.image.url }}" class="img-fluid rounded">
        <!-- </div> -->
    </div>
{% endblock %}

templates/home.html
{% extends "base.html" %}
{% load thumbnail %}

{% block body %}
    <div class="row">
        {% for post in posts%} 
            <div class="col-sm-6 col-md-3">
                <div class="card my-4">
                    {% thumbnail post.image "200x200" crop="center" as im %}
                    <img src="{{ im.url}}" class="card-img-top" alt="...">
                    {% endthumbnail %}
                <div class="card-body">
                <h5 class="card-title">Card title</h5>
                <p class="card-text">{{ post.text }}</p>
                <a href="{% url 'writeups:detail' post.id %}" class="btn btn-primary">View Full Image</a>
                </div>
            </div>
        </div> 
        {%endfor %}  
    </div>
{% endblock %} 

templates/homepage.html
{% extends "base.htm" %}

{% block title}Changed Title of the homepage{% endblock %}

{% block body %}
    {% for post in posts}
        {{ post.text }} written at {{ post.date }}

    {% endfor %}

{% endblock %}

templates/includes/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">Image Share</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'writeups:index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'writeups:post' %}">Add Image</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Pricing</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

templates/new_post.html
{% extends "base.html" %}

{% block title %} Upload a new image {% endblock %}

{% block body %}
<form method="POST" action="" enctype="multipart/form-data">
   {% csrf_token %}
{{ form.as_p }}
   <div>
      <button type="submit"> Submit Form</button>
   </div>
</form>
{% endblock %} 